In [45]:
import pyscf
import numpy
from pyscf import gto,scf

mol=gto.Mole()

mol.atom="""
O       0.0000000000     0.0000000000     0.0000000000
H       0.0000000000     0.0000000000     0.9706601900
"""
mol.basis='cc-pVTZ'
mol.cart=False
mol.charge=0
mol.ecp={}
mol.spin=1
mol.unit='Angstrom'
mol.verbose=0

mol.build()

mf=scf.UHF(mol)

mf.conv_tol=1e-12
mf.conv_tol_grad=1e-8
mf.direct_scf_tol=1e-13
mf.init_guess='minao'
mf.max_cycle=100
mf.max_memory=8000
mf.verbose=0

mf.kernel()
mf.spin_square()

(0.75606098062661875, 2.0060518244817294)

In [49]:
import pyscf
import numpy
from pyscf import gto,scf

mol=gto.Mole()

mol.atom="""
O       0.0000000000     0.0000000000     0.0000000000
H       0.0000000000     0.0000000000     0.9706601900
"""
mol.basis='cc-pVTZ'
mol.spin=1
mol.build()

mf=scf.UHF(mol)
mf.kernel()
scf.uhf.dip_moment(mol,mf.make_rdm1());

converged SCF energy = -75.4192257414501  <S^2> = 0.75606095  2S+1 = 2.0060518
Dipole moment(X, Y, Z, Debye):  0.00000, -0.00000,  1.78722


In [34]:
scf.uhf.dip_moment(mol,mf.make_rdm1());

Dipole moment(X, Y, Z, Debye): -0.00000,  0.00000,  1.78812


In [2]:
scf.uhf.dip_moment(mol,mf.make_rdm1())

Dipole moment(X, Y, Z, Debye): -0.00000, -0.00000,  1.78812


array([ -3.99479062e-15,  -7.84749205e-15,   1.78811633e+00])

In [3]:
scf.uhf.spin_square((mf.mo_coeff[:,mf.mo_occ>0],mf.mo_coeff[:,mf.mo_occ>0]),mf.get_ovlp())

(7.1054273576010019e-15, 1.0000000000000142)

In [4]:
mf.mulliken_meta(verbose=0)[1]

array([-0.34757223,  0.34757223])

In [5]:
mf.mulliken_pop(verbose=0)[1]

array([-0.25422653,  0.25422653])

In [6]:
import pyscf
import numpy
from pyscf import gto,scf

mol=gto.Mole()

mol.atom="""
O       0.0000000000     0.0000000000     0.0000000000
H       0.0000000000     0.0000000000     0.9706601900
"""
mol.basis='cc-pVTZ'
mol.cart=False
mol.charge=0
mol.ecp={}
mol.spin=1
mol.unit='Angstrom'
mol.verbose=0

mol.build()

mf=scf.UHF(mol)

mf.conv_tol=1e-12
mf.conv_tol_grad=1e-8
mf.direct_scf_tol=1e-13
mf.init_guess='1e'
mf.max_cycle=100
mf.max_memory=8000
mf.verbose=0

mf.kernel()

-75.41922574145255

In [7]:
scf.uhf.dip_moment(mol,mf.make_rdm1())

Dipole moment(X, Y, Z, Debye):  0.00000, -0.00000,  1.78721


array([  3.88048411e-15,  -5.66171308e-15,   1.78721196e+00])

In [8]:
mf.spin_square()

(0.75606098537886979, 2.0060518292196439)

In [9]:
mf.mulliken_meta(verbose=0)[1]

array([-0.34606321,  0.34606321])

In [10]:
mf.mulliken_pop(verbose=0)[1]

array([-0.25245498,  0.25245498])

In [11]:
import pyscf
import numpy
from pyscf import gto,scf

mol=gto.Mole()

mol.atom="""
H       0.0000000000     0.0000000000     0.0000000000
H       0.0000000000     0.0000000000     0.9706601900
"""
mol.basis='cc-pVTZ'
mol.cart=False
mol.charge=0
mol.ecp={}
mol.spin=0
mol.unit='Angstrom'
mol.verbose=0

mol.build()

mf=scf.RKS(mol)

In [21]:
mf.grids.__dict__

{'_keys': {'atom_grid',
  'atomic_radii',
  'becke_scheme',
  'coords',
  'level',
  'mol',
  'non0tab',
  'prune',
  'radi_method',
  'radii_adjust',
  'stdout',
  'symmetry',
  'verbose',
  'weights'},
 'atom_grid': {},
 'atomic_radii': array([ 0.        ,  0.66140414,  2.64561657,  2.74010288,  1.98421243,
         1.60626721,  1.32280829,  1.22832198,  1.13383567,  0.94486306,
         2.83458919,  3.40150702,  2.83458919,  2.36215766,  2.07869874,
         1.88972612,  1.88972612,  1.88972612,  3.40150702,  4.15739747,
         3.40150702,  3.0235618 ,  2.64561657,  2.55113027,  2.64561657,
         2.64561657,  2.64561657,  2.55113027,  2.55113027,  2.55113027,
         2.55113027,  2.45664396,  2.36215766,  2.17318504,  2.17318504,
         2.17318504,  3.59047964,  4.44085639,  3.77945225,  3.40150702,
         2.92907549,  2.74010288,  2.74010288,  2.55113027,  2.45664396,
         2.55113027,  2.64561657,  3.0235618 ,  2.92907549,  2.92907549,
         2.74010288,  2.74010288

In [2]:
import pyscf
import numpy
from pyscf import gto,scf

mol=gto.Mole()

mol.atom="""
H 0.0 0.0 0.0
F 0.0 0.0 2.0
"""
mol.basis='cc-pVTZ'
mol.cart=False
mol.charge=0
mol.ecp={}
mol.spin=0
mol.unit='Angstrom'
mol.verbose=0

mol.build()

mf=scf.RKS(mol)

mf.conv_tol=1e-12
mf.conv_tol_grad=1e-8
mf.direct_scf_tol=1e-13
mf.init_guess='1e'
mf.max_cycle=100
mf.max_memory=8000
mf.verbose=0
mf.small_rho_cutoff=1e-14
mf.xc='HF,P86'
mf.grids.atom_grid={'H': (500,974),'F': (500,974)}

mf.kernel()

KeyboardInterrupt: 

In [1]:
import pyscf
from pyscf import gto,scf,dft

def scf(method,molecule,basis,
        cart=False,charge=0,ecp={},spin=0,unit='Angstrom',
        conv_tol=1e-12,conv_tol_grad=1e-8,direct_scf_tol=1e-13,init_guess='atom',max_cycle=100,max_memory=8000,
        #xc=None,nlc=None,xc_grid=3,nlc_grid=3,
        #atomic_radii='BRAGG',becke_scheme='becke',prune='nwchem',radi_method='treutler_ahlrichs',radii_adjust='treutler',
        xc=None,nlc=None,xc_grid=(99,590),nlc_grid=(50,194),
        atomic_radii='BRAGG',becke_scheme='becke',prune=None,radi_method='gauss_chebyshev',radii_adjust=None,
        verbose=4):

    mol=gto.Mole()
    mol.atom=molecule
    mol.basis=basis
    mol.cart=cart
    mol.charge=charge
    mol.ecp=ecp
    mol.spin=spin
    mol.unit=unit
    mol.verbose=verbose
    mol.build()

    if method=='RHF' or method=='ROHF' or (method=='HF' and spin==0):
        mf=scf.RHF(mol)
    elif method=='UHF' or (method=='HF' and spin!=0):
        mf=scf.UHF(mol)
    elif method=='RKS' or method=='ROKS' or ((method=='KS' or method=='DFT') and spin==0):
        mf=scf.RKS(mol)
        DFT=True
    elif method=='UKS' or ((method=='KS' or method=='DFT') and spin!=0):
        mf=scf.UKS(mol)
        DFT=True
        
    mf.conv_tol=conv_tol
    mf.conv_tol_grad=conv_tol_grad
    mf.direct_scf_tol=direct_scf_tol
    mf.init_guess=init_guess
    mf.max_cycle=max_cycle
    mf.max_memory=max_memory
    mf.verbose=verbose

    if DFT:

        mf.xc=xc
        mf.nlc=nlc
        
        if isinstance(xc_grid,int):
            mf.grids.level=xc_grid
        elif isinstance(xc_grid,str):
            if xc_grid[0]=='(' and xc_grid[-1]==')':
                mf.grids.atom_grid=xc_grid
            else:
                print "CRASH"
        elif isinstance(xc_grid,dict):
            mf.grids.atom_grid=xc_grid
        else:
            print "CRASH"

        if isinstance(nlc_grid,int):
            mf.nlc_grids.level=nlc_grid
        elif isinstance(nlc_grid,str):
            if nlc_grid[0]=='(' and nlc_grid[-1]==')':
                mf.nlc_grids.atom_grid=nlc_grid
            else:
                print "CRASH"
        elif isinstance(nlc_grid,dict):
            mf.nlc_grids.atom_grid=nlc_grid
        else:
            print "CRASH"

        if atomic_radii=='BRAGG':
            mf.grids.atomic_radii=dft.radi.BRAGG_RADII
            mf.nlc_grids.atomic_radii=dft.radi.BRAGG_RADII
        elif atomic_radii=='COVALENT':
            mf.grids.atomic_radii=dft.radi.COVALENT_RADII
            mf.nlc_grids.atomic_radii=dft.radi.COVALENT_RADII
        else:
            print "CRASH"

        if becke_scheme=='becke':
            mf.grids.becke_scheme=dft.gen_grid.original_becke
            mf.nlc_grids.becke_scheme=dft.gen_grid.original_becke
        elif becke_scheme=='stratmann':
            mf.grids.becke_scheme=dft.gen_grid.stratmann
            mf.nlc_grids.becke_scheme=dft.gen_grid.stratmann
        else:
            print "CRASH"

        if prune=='nwchem':
            mf.grids.prune=dft.gen_grid.nwchem_prune
            mf.nlc_grids.prune=dft.gen_grid.nwchem_prune
        elif prune=='sg1':
            mf.grids.prune=dft.gen_grid.sg1_prune
            mf.nlc_grids.prune=dft.gen_grid.sg1_prune
        elif prune=='treutler':
            mf.grids.prune=dft.gen_grid.treutler_prune
            mf.nlc_grids.prune=dft.gen_grid.treutler_prune
        elif prune=='None' or prune==None:
            mf.grids.prune=None
            mf.nlc_grids.prune=None
        else:
            print "CRASH"

        if radi_method=='treutler' or radi_method=='ahlrichs' or radi_method=='treutler_ahlrichs':
            mf.grids.radi_method=dft.radi.treutler_ahlrichs
            mf.nlc_grids.radi_method=dft.radi.treutler_ahlrichs
        elif radi_method=='delley':
            mf.grids.radi_method=dft.radi.delley
            mf.nlc_grids.radi_method=dft.radi.delley
        elif radi_method=='mura_knowles' or radi_method=='mura' or radi_method=='knowles':
            mf.grids.radi_method=dft.radi.mura_knowles
            mf.nlc_grids.radi_method=dft.radi.mura_knowles
        elif radi_method=='gauss_chebyshev' or radi_method=='gauss' or radi_method=='chebyshev':
            mf.grids.radi_method=dft.radi.gauss_chebyshev
            mf.nlc_grids.radi_method=dft.radi.gauss_chebyshev
        else:
            print "CRASH"

        if radii_adjust=='original_becke':
            mf.grids.radii_adjust=dft.radi.treutler_atomic_radii_adjust
            mf.nlc_grids.radii_adjust=dft.radi.treutler_atomic_radii_adjust
        elif radii_adjust=='stratmann':
            mf.grids.radii_adjust=dft.radi.becke_atomic_radii_adjust
            mf.nlc_grids.radii_adjust=dft.radi.becke_atomic_radii_adjust
        elif radii_adjust=='None' or radii_adjust==None:
            mf.grids.radii_adjust=None
            mf.nlc_grids.radii_adjust=None
        else:
            print "CRASH"

        mf.small_rho_cutoff=small_rho_cutoff

    return mf.kernel()

In [2]:
import pyscf
from pyscf import gto,scf,dft

In [3]:
mol=gto.Mole()

mol.atom="""
O  -1.551007  -0.114520   0.000000
H  -1.934259   0.762503   0.000000
H  -0.599677   0.040712   0.000000
O   1.350625   0.111469   0.000000
H   1.680398  -0.373741  -0.758561
H   1.680398  -0.373741   0.758561"""
mol.basis='aug-cc-pVDZ'
mol.cart=False
mol.charge=0
mol.ecp={}
mol.spin=0
mol.unit='Angstrom'
mol.verbose=0

mol.build()

mf=scf.RKS(mol)

In [5]:
mf.grids.__dict__

{'_keys': {'atom_grid',
  'atomic_radii',
  'becke_scheme',
  'coords',
  'level',
  'mol',
  'non0tab',
  'prune',
  'radi_method',
  'radii_adjust',
  'stdout',
  'symmetry',
  'verbose',
  'weights'},
 'atom_grid': {},
 'atomic_radii': array([ 0.        ,  0.66140414,  2.64561657,  2.74010288,  1.98421243,
         1.60626721,  1.32280829,  1.22832198,  1.13383567,  0.94486306,
         2.83458919,  3.40150702,  2.83458919,  2.36215766,  2.07869874,
         1.88972612,  1.88972612,  1.88972612,  3.40150702,  4.15739747,
         3.40150702,  3.0235618 ,  2.64561657,  2.55113027,  2.64561657,
         2.64561657,  2.64561657,  2.55113027,  2.55113027,  2.55113027,
         2.55113027,  2.45664396,  2.36215766,  2.17318504,  2.17318504,
         2.17318504,  3.59047964,  4.44085639,  3.77945225,  3.40150702,
         2.92907549,  2.74010288,  2.74010288,  2.55113027,  2.45664396,
         2.55113027,  2.64561657,  3.0235618 ,  2.92907549,  2.92907549,
         2.74010288,  2.74010288

In [1]:
import pyscf,numpy,time

from pyscf import gto,scf

mol=gto.Mole()

mol.atom="""
C 0.0 0.0 0.0
C 0.0 0.0 1.24
"""
mol.basis='cc-pVTZ'
mol.cart=False
mol.charge=0
mol.spin=0
mol.unit='Angstrom'
mol.verbose=4

mol.build()

mf=scf.RHF(mol)

mf.conv_tol=1e-12
mf.conv_tol_grad=1e-8
mf.direct_scf_tol=1e-13
mf.init_guess='minao'
mf.max_cycle=1000
mf.max_memory=8000
mf.verbose=4

mf.kernel()


System: ('Linux', 'gund', '4.13.0-37-generic', '#42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018', 'x86_64', 'x86_64')  Threads 1
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609]
numpy 1.12.1  scipy 0.19.0
Date: Thu Mar 29 02:01:35 2018
PySCF version 1.5a
PySCF path  /home/narbe/pyscf/pyscf
GIT HEAD      ref: refs/heads/dev
GIT dev branch  2f68f0da06e3ea0ceed90858f3924416304688a2
config None

[INPUT] VERBOSE 4
[INPUT] num atoms = 2
[INPUT] num electrons = 12
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry False subgroup None
[INPUT]  1 C      0.000000000000   0.000000000000   0.000000000000 AA    0.000000000000   0.000000000000   0.000000000000 Bohr
[INPUT]  2 C      0.000000000000   0.000000000000   1.240000000000 AA    0.000000000000   0.000000000000   2.343260394461 Bohr
[INPUT] ---------------- BASIS SET ---------------- 
[INPUT] l, kappa, [nprim/nctr], expnt,             c_1 c_2 ...
[INPUT] C
[INPUT] 0    0    [8    /2   ]  8236

-75.401449222617558

In [3]:
for i in range(5):
    tmp=mf.stability(internal=True,external=False)[0]
    nalpha=numpy.count_nonzero(mf.mo_occ)
#    mf.kernel(dm0=numpy.dot(tmp[0][:,:nalpha],tmp[0].T[0:nalpha])+numpy.dot(tmp[1][:,0:nbeta],tmp[1].T[0:nbeta]))
    mf.kernel(dm0=(2*numpy.dot(tmp[:,:nalpha],tmp.T[:nalpha])))

print mf.spin_square()

RHF/RKS wavefunction is stable in the intenral stablity analysis


******** <class 'pyscf.scf.hf.RHF'> flags ********
method = RHF
initial guess = minao
damping factor = 0
level shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
DIIS start cycle = 1
DIIS space = 8
SCF tol = 1e-12
SCF gradient tol = 1e-08
max. SCF cycles = 1000
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/narbe/Tutorial_PySCF/tmp5mPYmH
max_memory 8000 MB (current use 99 MB)
init E= -75.4359034576601
  HOMO = -0.468448824662235  LUMO = -0.0996558667716233
cycle= 1 E= -75.43590345766  delta_E= 8.53e-14  |g|= 1.71e-09  |ddm|= 3.29e-09
  HOMO = -0.468448824576196  LUMO = -0.0996558667094802
Extra cycle  E= -75.43590345766  delta_E= -4.26e-14  |g|= 1.56e-09  |ddm|= 2.41e-09
converged SCF energy = -75.43590345766
RHF/RKS wavefunction is stable in the intenral stablity analysis


******** <class 'pyscf.scf.hf.RHF'> flags ********
method = RHF
initial guess = minao
damping factor = 0
level shi

AttributeError: 'RHF' object has no attribute 'spin_square'

In [6]:
numpy.shape(mf.stability(internal=True,external=False)[0])

RHF/RKS wavefunction has an internal instablity


(60, 60)

In [27]:
import pyscf,numpy,time

from pyscf import gto,scf

mol=gto.Mole()

mol.atom="""
C 0.0 0.0 0.0
C 0.0 0.0 1.24
"""
mol.basis='cc-pVTZ'
mol.cart=False
mol.charge=0
mol.spin=0
mol.unit='Angstrom'
mol.verbose=0

mol.build()

mf=scf.RKS(mol).newton()
mf.xc='B3LYP'
#mf.diis=scf.diis.DIIS()
mf.conv_tol=1e-12
mf.conv_tol_grad=1e-8
mf.direct_scf_tol=1e-13
mf.init_guess='minao'
mf.max_cycle=1000
mf.max_memory=8000
mf.verbose=4

mf.kernel()

  HOMO = -0.355357450831866  LUMO = -0.316479408785707


******** <class 'pyscf.dft.rks.RKS'> Newton solver flags ********
SCF tol = 1e-12
conv_tol_grad = 1e-08
max. SCF cycles = 1000
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/narbe/Tutorial_PySCF/tmpFSTk7k
max_cycle_inner = 12
max_stepsize = 0.05
ah_start_tol = 1e+09
ah_level_shift = 0
ah_conv_tol = 1e-12
ah_lindep = 1e-14
ah_start_cycle = 1
ah_max_cycle = 40
ah_grad_trust_region = 2.5
kf_interval = 4
kf_trust_region = 5
canonicalization = True
max_memory 8000 MB (current use 140 MB)
Initial guess |g|= 0.450974

WARN: HOMO -0.252487324450054 == LUMO -0.252487324450054

macro= 0  E= -75.1989124119599  delta_E= -75.1989  |g|= 0.450974  2 KF 5 JK
macro= 1  E= -75.1999237365271  delta_E= -0.00101132  |g|= 0.0658285  2 KF 5 JK
macro= 2  E= -75.1999526645022  delta_E= -2.8928e-05  |g|= 0.0126293  2 KF 5 JK
macro= 3  E= -75.1999547974366  delta_E= -2.13293e-06  |g|= 0.000543385  3 KF 9 JK
macro= 4  E= -75.199

KeyboardInterrupt: 

In [3]:
mf=mf.newton()

In [6]:
from pyscf import lib
from pyscf.scf import diis

In [13]:
isinstance(diis.EDIIS(), lib.diis.DIIS)

True

In [4]:
mf.conv_tol=1e-12
mf.conv_tol_grad=1e-8
mf.direct_scf_tol=1e-13
mf.init_guess='minao'
mf.max_cycle=1000
mf.max_memory=8000
mf.verbose=4

mf.kernel()

  HOMO = -0.313940844097438  LUMO = -0.235755796569622




******** <class 'pyscf.scf.hf.RHF'> flags ********
method = RHF
initial guess = minao
damping factor = 0
level shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
DIIS start cycle = 1
DIIS space = 8
SCF tol = 1e-09
SCF gradient tol = None
max. SCF cycles = 50
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/narbe/Tutorial_PySCF/tmpp3B1_E
max_memory 4000 MB (current use 94 MB)
******** <class 'pyscf.scf.hf.RHF'> Newton solver flags ********
SCF tol = 1e-12
conv_tol_grad = 1e-08
max. SCF cycles = 1000
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/narbe/Tutorial_PySCF/tmpp3B1_E
max_cycle_inner = 12
max_stepsize = 0.05
ah_start_tol = 1e+09
ah_level_shift = 0
ah_conv_tol = 1e-12
ah_lindep = 1e-14
ah_start_cycle = 1
ah_max_cycle = 40
ah_grad_trust_region = 2.5
kf_interval = 4
kf_trust_region = 5
canonicalization = True
max_memory 8000 MB (current use 94 MB)
Initial guess |g|

macro= 98  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 99  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 100  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 101  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 102  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 103  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 104  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 105  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 106  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 107  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 108  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 109  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 110  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 111  E= -75.4014492226174  delta_

macro= 209  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 210  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 211  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 212  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 213  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 214  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 215  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 216  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 217  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 218  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 219  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 220  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 221  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 222  E= -75.4014492226174  delt

macro= 320  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 321  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 322  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 323  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 324  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 325  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 326  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 327  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 328  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 329  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 330  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 331  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 332  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 333  E= -75.4014492226174  delt

macro= 431  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 432  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 433  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 434  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 435  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 436  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 437  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 438  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 439  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 440  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 441  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 442  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 443  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 444  E= -75.4014492226174  delt

macro= 542  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 543  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 544  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 545  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 546  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 547  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 548  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 549  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 550  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 551  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 552  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 553  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 554  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 555  E= -75.4014492226174  delt

macro= 653  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 654  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 655  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 656  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 657  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 658  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 659  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 660  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 661  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 662  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 663  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 664  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 665  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 666  E= -75.4014492226174  delt

macro= 764  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 765  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 766  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 767  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 768  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 769  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 770  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 771  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 772  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 773  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 774  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 775  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 776  E= -75.4014492226174  delta_E= 0  |g|= 2.85444e-08  1 KF 2 JK
macro= 777  E= -75.4014492226174  delt

KeyboardInterrupt: 

In [30]:
import pyscf,numpy,time

from pyscf import gto,scf

mol=gto.Mole()

mol.atom="""
O  -1.551007  -0.114520   0.000000
H  -1.934259   0.762503   0.000000
H  -0.599677   0.040712   0.000000"""
mol.basis='cc-pVTZ'
mol.cart=False
mol.charge=0
mol.spin=0
mol.unit='Angstrom'
mol.verbose=0

mol.build()

mf=scf.RKS(mol)
mf.xc='B3LYP'
mf.conv_tol=1e-12
mf.conv_tol_grad=1e-8
mf.direct_scf_tol=1e-13
mf.init_guess='minao'
mf.max_cycle=1000
mf.max_memory=8000
mf.verbose=4

mf.kernel()



******** <class 'pyscf.dft.rks.RKS'> flags ********
method = RKS-RHF
initial guess = minao
damping factor = 0
level shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
DIIS start cycle = 1
DIIS space = 8
SCF tol = 1e-12
SCF gradient tol = 1e-08
max. SCF cycles = 1000
direct_scf = True
direct_scf_tol = 1e-13
chkfile to save SCF result = /home/narbe/Tutorial_PySCF/tmpCZaRZy
max_memory 8000 MB (current use 198 MB)
XC functionals = B3LYP
small_rho_cutoff = 1e-07
init E= -76.3496381118377
  HOMO = -0.426497401964482  LUMO = -0.00865479205750686
cycle= 1 E= -76.3321843561751  delta_E= 0.0175  |g|= 0.723  |ddm|= 1.03
  HOMO = -0.141158654920159  LUMO = 0.0532158264692848
cycle= 2 E= -76.2083994980854  delta_E= 0.124  |g|= 1.11  |ddm|= 0.747
  HOMO = -0.312390107451829  LUMO = 0.0235757522798764
cycle= 3 E= -76.4225588500363  delta_E= -0.214  |g|= 0.029  |ddm|= 0.463
  HOMO = -0.306368913442207  LUMO = 0.0271917109595087
cycle= 4 E= -76.4227067133895  delta_E= -0.000148  |g|= 0.00515  |dd

-76.422711379555921

In [43]:
import pyscf,numpy,time

from pyscf import gto,scf

mol=gto.Mole()

mol.atom="""
O  -1.551007  -0.114520   0.000000
H  -1.934259   0.762503   0.000000
H  -0.599677   0.040712   0.000000"""
mol.basis='cc-pVDZ'
mol.cart=False
mol.charge=0
mol.spin=0
mol.unit='Angstrom'
mol.verbose=4

mol.build()

mf=scf.RHF(mol)
mf.xc='B3LYP'
mf.conv_tol=1e-12
mf.conv_tol_grad=1e-8
mf.direct_scf_tol=1e-13
mf.init_guess='minao'
mf.max_cycle=1000
mf.max_memory=8000
mf.verbose=4

mf.kernel()

System: ('Linux', 'gund', '4.13.0-37-generic', '#42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018', 'x86_64', 'x86_64')  Threads 1
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609]
numpy 1.12.1  scipy 0.19.0
Date: Thu Mar 29 22:27:27 2018
PySCF version 1.5a
PySCF path  /home/narbe/pyscf/pyscf
GIT HEAD      ref: refs/heads/dev
GIT dev branch  2f68f0da06e3ea0ceed90858f3924416304688a2
config None

[INPUT] VERBOSE 4
[INPUT] num atoms = 3
[INPUT] num electrons = 10
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry False subgroup None
[INPUT]  1 O     -1.551007000000  -0.114520000000   0.000000000000 AA   -2.930978447283  -0.216411435785   0.000000000000 Bohr
[INPUT]  2 H     -1.934259000000   0.762503000000   0.000000000000 AA   -3.655219763975   1.440921839159   0.000000000000 Bohr
[INPUT]  3 H     -0.599677000000   0.040712000000   0.000000000000 AA   -1.133225293201   0.076934529983   0.000000000000 Bohr
[INPUT] ---------------- BASIS SET 

-76.026603096155384

In [45]:
import pyscf,numpy,time

from pyscf import gto,scf

mol=gto.Mole()

mol.atom="""
O  -1.551007  -0.114520   0.000000
H  -1.934259   0.762503   0.000000
H  -0.599677   0.040712   0.000000"""
mol.basis='cc-pVDZ'
mol.cart=False
mol.charge=0
mol.spin=0
mol.unit='Angstrom'
mol.verbose=4

mol.build()

mf=scf.RHF(mol)
mf.xc='B3LYP'
mf.conv_check=True
mf.conv_tol=1e-12
mf.conv_tol_grad=1e-8
mf.direct_scf_tol=1e-13
mf.init_guess='minao'
mf.max_cycle=1000
mf.max_memory=8000
mf.verbose=4

mf.kernel()

System: ('Linux', 'gund', '4.13.0-37-generic', '#42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018', 'x86_64', 'x86_64')  Threads 1
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609]
numpy 1.12.1  scipy 0.19.0
Date: Thu Mar 29 22:31:10 2018
PySCF version 1.5a
PySCF path  /home/narbe/pyscf/pyscf
GIT HEAD      ref: refs/heads/dev
GIT dev branch  2f68f0da06e3ea0ceed90858f3924416304688a2
config None

[INPUT] VERBOSE 4
[INPUT] num atoms = 3
[INPUT] num electrons = 10
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry False subgroup None
[INPUT]  1 O     -1.551007000000  -0.114520000000   0.000000000000 AA   -2.930978447283  -0.216411435785   0.000000000000 Bohr
[INPUT]  2 H     -1.934259000000   0.762503000000   0.000000000000 AA   -3.655219763975   1.440921839159   0.000000000000 Bohr
[INPUT]  3 H     -0.599677000000   0.040712000000   0.000000000000 AA   -1.133225293201   0.076934529983   0.000000000000 Bohr
[INPUT] ---------------- BASIS SET 

-76.026603096155384